version: "3.3"
services:
  kirhub:
    image: sc-registry.fredhutch.org/kirhub:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kirhub.rule=Host(`kirhub.fredhutch.org`)"
        - "traefik.http.routers.kirhub-secured.rule=Host(`kirhub.fredhutch.org`)"
        - "traefik.http.routers.kirhub.entrypoints=web,web-secured"
        - "traefik.http.services.kirhub.loadbalancer.server.port=3838"
        - "traefik.http.routers.kirhub.tls=true"

networks:
  sc-swarm-net:
    external: true
